apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-php-app
  template:
    metadata:
      labels:
        app: my-php-app
    spec:
      containers:
        - name: my-php-container
          image: tahiranawaz/php-webapp:031cee84613d4e98e78e96b9ab9ddcbebd72c8a0
          ports:
            - containerPort: 80
          env:
            - name: DB_SERVER
              value: "my-mysql-service"
            - name: DB_USERNAME
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_DATABASE
              value: "testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: my-php-service1
spec:
  selector:
    app: my-php-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081 
  type: NodePort
  template:
    spec:
      containers:
        - image: tahiranawaz/php-webapp:228a14176bbcd85578d813f70636535b5523e4b4
