apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-php-app
  template:
    metadata:
      labels:
        app: my-php-app
    spec:
      containers:
        - name: my-php-container
          image: tahiranawaz/php-webapp:b4a4f6fa96123aca07866a5fa5e1155ea052d6c1
          ports:
            - containerPort: 80
          env:
            - name: DB_SERVER
              value: "my-mysql-service"
            - name: DB_USERNAME
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_DATABASE
              value: "testdb"
