name: CI/CD for PHP Frontend with Argo CD

on:
  push:
    branches: 
      - main
    #  - none

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Custom Image Name
        id: image
        run: |
          IMAGE_NAME="tahiranawaz/php-webapp:tahira-${{ github.sha::7 }}-$(date +%Y%m%d%H%M%S)"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update Image in PHP Deployment Manifest
        run: |
          yq e 'select(.kind == "Deployment") | .spec.template.spec.containers[0].image = env(IMAGE_NAME)' k8s/php-deployment.yaml > tmp.yaml
          yq e 'select(.kind != "Deployment")' k8s/php-deployment.yaml >> tmp.yaml
          mv tmp.yaml k8s/php-deployment.yaml

          git diff --quiet k8s/php-deployment.yaml || {
            git config --global user.email "ci@github.com"
            git config --global user.name "GitHub CI"
            git add k8s/php-deployment.yaml
            git commit -m "Update PHP image to $IMAGE_NAME"
            git push
          }
