name: CI/CD for PHP Frontend with Argo CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: tahira-version1-${{ github.run_id }}-${{ github.run_number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t tahiranawaz/php-webapp:${{ env.IMAGE_TAG }} .
          docker push tahiranawaz/php-webapp:${{ env.IMAGE_TAG }}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update Image in Deployment YAML
        run: |
          yq e 'select(.kind == "Deployment") |= (.spec.template.spec.containers[0].image = "tahiranawaz/php-webapp:${{ env.IMAGE_TAG }}")' k8s/php-deployment.yaml > tmp.yaml
          mv tmp.yaml k8s/php-deployment.yaml

          # yq e '(.kind == "Deployment") |= with(.spec.template.spec.containers[]; .image = "tahiranawaz/php-webapp:tahira-version1")' -i k8s/php-deployment.yaml


          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub CI"

          git add k8s/php-deployment.yaml
          git commit -m "Update image to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
          git push || echo "Nothing to push"
