name: CI/CD for PHP Frontend with Argo CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t tahiranawaz/php-webapp:${{ github.sha }} .
          docker push tahiranawaz/php-webapp:${{ github.sha }}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update Image in PHP Deployment Manifest
        run: |
          yq e '.spec.template.spec.containers[0].image = "tahiranawaz/php-webapp:${{ github.sha }}"' -i k8s/php-deployment.yaml
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub CI"
          git add k8s/php-deployment.yaml
          git commit -m "Update PHP image to ${{ github.sha }}"
          git push
